<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PISO.Contracts\PISO.Contracts.csproj" />
        <ProjectReference Include="..\PISO.Entities\PISO.Entities.csproj" />
        <ProjectReference Include="..\PISO.Shared\PISO.Shared.csproj" />
    </ItemGroup>

</Project>
